<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Employee::insert([
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '197506252021211003',
                'slug' => 'subono-s-t-m-t',
                'name' => 'Subono, S.T.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'subono.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '197509272021211002',
                'slug' => 'herman-yuliandoko-s-t-m-t',
                'name' => 'Herman Yuliandoko, S.T.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'herman.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '197601222021211001',
                'slug' => 'mohamad-dimyati-ayatullah-s-t-m-kom',
                'name' => 'Mohamad Dimyati Ayatullah, S.T.,M.Kom',
                'gender' => 'Laki-Laki',
                'image' => 'dimyati.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '197704042021211004',
                'slug' => 'dedy-hidayat-kusuma-s-t-m-cs',
                'name' => 'Dedy Hidayat Kusuma, S.T.,M.Cs',
                'gender' => 'Laki-Laki',
                'image' => 'dedy.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '197806132014041001',
                'slug' => 'muhammad-fuad-alharis-s-t-m-t',
                'name' => 'Muhammad Fuad Alharis, S.T.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'fuad.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198010222015041001',
                'slug' => 'i-wayan-suardinata-s-kom-m-kot',
                'name' => 'I Wayan Suardinata, S.Kom.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'wayan.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198301192021211006',
                'slug' => 'moh-nur-shodiq-s-t-m-t',
                'name' => 'Moh. Nur Shodiq, S.T.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'shodiq.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198310202014042001',
                'slug' => 'eka-mistiko-rini-s-kom-m-kom',
                'name' => 'Eka Mistiko Rini, S.Kom.,M.Kom',
                'gender' => 'Perempuan',
                'image' => 'eka.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198311052015041001',
                'slug' => 'devit-suwardiyanto-s-si-m-t',
                'name' => 'Devit Suwardiyanto, S.Si.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'devit.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198403052021212004',
                'slug' => 'dianni-yusuf-s-kom-m-kom',
                'name' => 'Dianni Yusuf, S.Kom.,M.Kom',
                'gender' => 'Perempuan',
                'image' => 'dianni.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198403112019031005',
                'slug' => 'endi-sailul-haq-s-t-m-kom',
                'name' => 'Endi Sailul Haq, S.T.,M.Kom',
                'gender' => 'Perempuan',
                'image' => 'endi.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '198404032019032012',
                'slug' => 'vivien-arief-wardhany-s-t-m-t',
                'name' => 'Vivien Arief Wardhany, S.T.,M.T',
                'gender' => 'Perempuan',
                'image' => 'vivien.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '2013.36.106',
                'slug' => 'farizqi-panduardi-s-st-m-t',
                'name' => 'Farizqi Panduardi, S.ST.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'farizqi.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199004192018031001',
                'slug' => 'junaedi-adi-prasetyo-s-st-m-sc',
                'name' => 'Junaedi Adi Prasetyo, S.ST.,M.Sc',
                'gender' => 'Laki-Laki',
                'image' => 'junaidi.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199009052019031024',
                'slug' => 'sepyan-purnama-kristanto-s-kom-m-kom',
                'name' => 'Sepyan Purnama Kristanto, S.Kom.,M.Kom',
                'gender' => 'Laki-Laki',
                'image' => 'sepyan.jpeg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199010052014041002',
                'slug' => 'alfin-hidayat-s-t-m-t',
                'name' => 'Alfin Hidayat, S.T.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'alfin.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199104202018031002',
                'slug' => 'alif-akbar-fitriawan-s-pd-m-kom',
                'name' => 'Alif Akbar Fitrawan, S.Pd.,M.Kom',
                'gender' => 'Laki-Laki',
                'image' => 'alif.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199203302019031012',
                'slug' => 'lutfi-hakim-s-pd-m-t',
                'name' => 'Lutfi Hakim, S.Pd.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'lutfi.jpeg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '2010.36.048',
                'slug' => 'agus-priyo-utomo-s-st-mtr-kom',
                'name' => 'Agus Priyo Utomo, S.ST.,M.Tr.Kom',
                'gender' => 'Laki-Laki',
                'image' => 'agus.jpeg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199202272020122019',
                'slug' => 'ruth-ema-febrita-s-pd-m-kom',
                'name' => 'Ruth Ema Febrita, S.Pd.,M.Kom',
                'gender' => 'Perempuan',
                'image' => 'ema.jpeg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '2018.36.214',
                'slug' => 'galih-hendra-wibowo-s-tr-kom-m-t',
                'name' => 'Galih Hendra Wibowo, S.Tr.Kom.,M.T',
                'gender' => 'Laki-Laki',
                'image' => 'galih.jpg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '199209212020122021',
                'slug' => 'arum-randary-ratri-s-si-m-si',
                'name' => 'Arum Andary Ratri, S.Si.,M.Si',
                'gender' => 'Perempuan',
                'image' => 'arum.jpeg',
            ],
            [
                'employee_type_id' => 1,
                'user_id' => 1,
                'identity_number' => '2021.36.248',
                'slug' => 'indira-nuansa-ratri-s-m-m-sm',
                'name' => 'Indira Nuansa Ratri, S.M.,M.SM',
                'gender' => 'Perempuan',
                'image' => 'indira.jpeg',
            ],
            [
                'employee_type_id' => 3,
                'user_id' => 1,
                'identity_number' => '198711032021212001',
                'slug' => 'dian-mujiani-s-e',
                'name' => 'Dian Mujiani, S.E',
                'gender' => 'Perempuan',
                'image' => 'dian.jpeg',
            ],
            [
                'employee_type_id' => 2,
                'user_id' => 1,
                'identity_number' => '198810152014041001',
                'slug' => 'fendi-hermawanto-a-md',
                'name' => 'Fendi Hermawanto, A.Md',
                'gender' => 'Laki-Laki',
                'image' => 'fendi.jpg',
            ],
            [
                'employee_type_id' => 2,
                'user_id' => 1,
                'identity_number' => '2013.36.105',
                'slug' => 'muhamad-nur-hariri-a-md',
                'name' => 'Muhammad Nur Hariri, A.Md',
                'gender' => 'Laki-Laki',
                'image' => 'hariri.jpg',
            ],
            [
                'employee_type_id' => 2,
                'user_id' => 1,
                'identity_number' => '198705032014041001',
                'slug' => 'hilda-jaya-habibi-a-md',
                'name' => 'Hida Jaya Habibi, A.Md',
                'gender' => 'Laki-Laki',
                'image' => 'hidajaya.jpg',
            ],
            [
                'employee_type_id' => 2,
                'user_id' => 1,
                'identity_number' => '2013.36.108',
                'slug' => 'nur-cholik-hasyim-a-md',
                'name' => 'Nur Cholik Hasyim, A.Md',
                'gender' => 'Laki-Laki',
                'image' => 'cholik.jpg',
            ],
        ]);
    }
}